#!/bin/bash

# UNIX INSTALL-------------------------
ln -sv ~/dotfiles/.bashrc ~
ln -sv ~/dotfiles/.tmux.conf ~

if [ -d "~/.emacs.d/" ]; then
    if [ -L "~/.emacs.d" ]; then
	# symlink
	rm -r "~/.emacs.d"
	echo "removed symlink: ~/.emacs.d"
    else
	# directory
	rmdir -r "~/.emacs.d"
	echo "removed dir: ~/.emacs.d"
    fi
fi
ln -sv ~/dotfiles/.emacs.d/* ~/.emacs.d/
#--------------------------------------

# MAC INSTALL (instructions, not scripted)

# ln -sv /Users/kvams/Documents/GitHub/dotfiles/.tmux.conf /Users/kvams
# ln -sv /Users/kvams/Documents/GitHub/dotfiles/.bashrc /Users/kvams
# mkdir /Users/kvams/.emacs.d
# ln -sv /Users/kvams/Documents/GitHub/dotfiles/.emacs.d/* /Users/kvams/.emacs.d
